export const PRIMARY_COLOR = "#1F2937";
export const SECONDARY_COLOR= "white";
export const TERTIARY_COLOR= "black";
export const COLOR_AZUL_PRINCIPAL= "#154360";
export const COLOR_ROJO_PRINCIPAL= "#7b241c";
export const COLOR_CELESTE_PRINCIPAL= "#5dade2";
export const COLOR_PLOMO_PRINCIPAL= "gray";
export const COLOR_FORNYTY_ESP= "rgba(0,0,0,0.5)";
export const COLOR_TRANSPARENT_ESP= "rgba(0,0,0,0.0)"